# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
warnings_are_errors: true,
r_github_packages: 
  - hemken/Statamarkdown
r_build_args: '',
r_check_args: '--as-cran',
pandoc: true,
latex: true,
fortran: true,
disable_homebrew: false,
use_devtools: TRUE
r: 'release'
after_success:
  - Rscript -e 'covr::codecov()'